CREATE DATABASE test_database2;
USE DATABASE test_database2;
SHOW DATABASES;
DROP DATABASE test_database;
CREATE DATABASE test_database;
UNDROP DATABASE test_database;

USE DATABASE test_database;
USE SCHEMA test_schema;
CREATE SCHEMA test_schema;
SHOW SCHEMAS ;
DESCRIBE DATABASE test_database;

DROP SCHEMA test_schema;
UNDROP SCHEMA test_schema;

CREATE TABLE TEST_TABLE (
	TEST_NUMBER NUMBER,
	TEST_VARCHAR VARCHAR,
	TEST_BOOLEAN BOOLEAN,
	TEST_DATE DATE,
	TEST_VARIANT VARIANT,
	TEST_GEOGRAPHY GEOGRAPHY
);
INSERT INTO TEST_DATABASE.TEST_SCHEMA.TEST_TABLE
  VALUES
  (28, 'ha!', True, '2024-01-01', NULL, NULL);
SELECT * FROM TEST_TABLE;


SHOW TABLES;

CREATE TABLE test_table2 (
	TEST_NUMBER NUMBER
);
INSERT INTO TEST_DATABASE.TEST_SCHEMA.TEST_TABLE2
  VALUES
  (42);
SELECT * FROM TEST_TABLE2;

DROP TABLE TEST_TABLE;
UNDROP TABLE TEST_TABLE;