show procedures;

SHOW PROCEDURES LIKE '%EMAIL%';

SELECT * FROM TASTY_BYTES.RAW_POS.ORDER_HEADER
LIMIT 100;

SELECT MAX(ORDER_TS), MIN(ORDER_TS) FROM TASTY_BYTES.RAW_POS.ORDER_HEADER
LIMIT 100;

SET MAX_TS = (SELECT MAX(ORDER_TS) FROM TASTY_BYTES.RAW_POS.ORDER_HEADER);

SELECT $MAX_TS;

SET CUTOFF_TS = (SELECT DATEADD('DAY',-180,$MAX_TS));

SELECT $MAX_TS,$CUTOFF_TS;

SELECT MAX(ORDER_TS) FROM TASTY_BYTES.RAW_POS.ORDER_HEADER
WHERE ORDER_TS < $CUTOFF_TS;


CREATE OR REPLACE PROCEDURE DELETE_OLD()
RETURNS BOOLEAN
LANGUAGE SQL
AS
$$
DECLARE 
    MAX_TS      TIMESTAMP;
    CUTOFF_TS   TIMESTAMP;
BEGIN
    MAX_TS      := (SELECT MAX(ORDER_TS) FROM TASTY_BYTES.RAW_POS.ORDER_HEADER);
    CUTOFF_TS   := (SELECT DATEADD('DAY',-180,:MAX_TS));
    DELETE FROM TASTY_BYTES.RAW_POS.ORDER_HEADER
    WHERE ORDER_TS < :CUTOFF_TS;
END;
$$
;


SHOW PROCEDURES LIKE '%DELETE_OLD%';
DESCRIBE PROCEDURE DELETE_OLD();

CALL DELETE_OLD();