USE ROLE ACCOUNTADMIN;

CREATE ROLE TASTY_DE;

SHOW GRANTS TO ROLE TASTY_DE;

SHOW GRANTS TO ROLE ACCOUNTADMIN;

GRANT ROLE TASTY_DE TO USER FELIPEXCORP;

USE ROLE TASTY_DE;

CREATE WAREHOUSE TASTY_DE_TEST;

GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE TASTY_DE;