CREATE WAREHOUSE IF NOT EXISTS ACME_ETL_WH
WITH
    WAREHOUSE_SIZE = 'X-Small'
    AUTO_SUSPEND = 5
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS ACME_BI_WH
WITH
    WAREHOUSE_SIZE = 'X-Small'
    AUTO_SUSPEND = 5
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS ACME_RETAIL_DB;


USE DATABASE ACME_RETAIL_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS DWH;
CREATE SCHEMA IF NOT EXISTS REPORTING;

CREATE TABLE RAW.CUSTOMERS_RAW
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    EMAIL VARCHAR,
    CITY VARCHAR,
    COUNTRY VARCHAR,
    CREATED_DATE DATE
);

CREATE TABLE RAW.PRODUCTS_RAW
(
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    PRICE NUMBER(10,2)
);

CREATE TABLE RAW.ORDERS_RAW
(
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    ORDER_DATE DATE,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(10,2)
);

INSERT INTO RAW.CUSTOMERS_RAW VALUES
(1,'Juan Perez','juan@test.com','Montreal','Canada','2025-01-01'),
(2,'Maria Lopez','maria@test.com','Bogota','Colombia','2025-02-01'),
(3,'John Smith','john@test.com','New York','USA','2025-03-01');

INSERT INTO RAW.PRODUCTS_RAW VALUES
(101,'Laptop','Technology',1200),
(102,'Mouse','Technology',50),
(103,'Desk','Furniture',500);

INSERT INTO RAW.ORDERS_RAW VALUES
(1001,1,101,'2026-01-10',1,1200),
(1002,1,102,'2026-01-11',2,100),
(1003,2,103,'2026-01-12',1,500),
(1004,3,101,'2026-01-15',1,1200);

CREATE TABLE STAGING.STG_CUSTOMERS AS
SELECT *
FROM RAW.CUSTOMERS_RAW;


CREATE TABLE STAGING.STG_PRODUCTS AS
SELECT *
FROM RAW.PRODUCTS_RAW;

CREATE TABLE STAGING.STG_ORDERS AS
SELECT *
FROM RAW.ORDERS_RAW;

CREATE TABLE DWH.DIM_CUSTOMER
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    EMAIL VARCHAR,
    CITY VARCHAR,
    COUNTRY VARCHAR
);

CREATE TABLE DWH.DIM_PRODUCT
(
    PRODUCT_KEY NUMBER AUTOINCREMENT,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    PRICE NUMBER(10,2)
);

CREATE TABLE DWH.FACT_SALES
(
    SALES_KEY NUMBER AUTOINCREMENT,
    ORDER_ID NUMBER,
    CUSTOMER_KEY NUMBER,
    PRODUCT_KEY NUMBER,
    ORDER_DATE DATE,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(10,2)
);


INSERT INTO DWH.DIM_CUSTOMER
(
CUSTOMER_ID,
CUSTOMER_NAME,
EMAIL,
CITY,
COUNTRY
)
SELECT
CUSTOMER_ID,
CUSTOMER_NAME,
EMAIL,
CITY,
COUNTRY
FROM STAGING.STG_CUSTOMERS;


INSERT INTO DWH.DIM_PRODUCT
(
PRODUCT_ID,
PRODUCT_NAME,
CATEGORY,
PRICE
)
SELECT
PRODUCT_ID,
PRODUCT_NAME,
CATEGORY,
PRICE
FROM STAGING.STG_PRODUCTS;


INSERT INTO DWH.FACT_SALES
(
ORDER_ID,
CUSTOMER_KEY,
PRODUCT_KEY,
ORDER_DATE,
QUANTITY,
TOTAL_AMOUNT
)
SELECT
O.ORDER_ID,
C.CUSTOMER_KEY,
P.PRODUCT_KEY,
O.ORDER_DATE,
O.QUANTITY,
O.TOTAL_AMOUNT

FROM STAGING.STG_ORDERS O

JOIN DWH.DIM_CUSTOMER C
ON O.CUSTOMER_ID=C.CUSTOMER_ID

JOIN DWH.DIM_PRODUCT P
ON O.PRODUCT_ID=P.PRODUCT_ID;


CREATE VIEW REPORTING.V_SALES AS

SELECT

F.ORDER_ID,
F.ORDER_DATE,
C.CUSTOMER_NAME,
C.COUNTRY,
P.PRODUCT_NAME,
P.CATEGORY,
F.QUANTITY,
F.TOTAL_AMOUNT

FROM DWH.FACT_SALES F

JOIN DWH.DIM_CUSTOMER C
ON F.CUSTOMER_KEY=C.CUSTOMER_KEY

JOIN DWH.DIM_PRODUCT P
ON F.PRODUCT_KEY=P.PRODUCT_KEY;


CREATE VIEW REPORTING.V_CUSTOMER_SALES AS

SELECT

COUNTRY,
CUSTOMER_NAME,
SUM(TOTAL_AMOUNT) TOTAL_SALES

FROM REPORTING.V_SALES

GROUP BY
COUNTRY,
CUSTOMER_NAME;



CREATE VIEW REPORTING.V_PRODUCT_SALES AS

SELECT

CATEGORY,
PRODUCT_NAME,
SUM(TOTAL_AMOUNT) TOTAL_SALES

FROM REPORTING.V_SALES

GROUP BY
CATEGORY,
PRODUCT_NAME;


SELECT *
FROM REPORTING.V_SALES;


-- Arquitectura recomendada

SHOW DATABASES;

--Paso 1 - Eliminar lo anterior 
DROP DATABASE IF EXISTS ACME_RETAIL_DB;

--Paso 2 - Crear las nuevas Databases
CREATE DATABASE IF NOT EXISTS ACME_RAW_DB;
CREATE DATABASE IF NOT EXISTS ACME_DWH_DB;
CREATE DATABASE IF NOT EXISTS ACME_ANALYTICS_DB;

--Paso 3 - Crear Schemas
--  RAW Database
CREATE SCHEMA IF NOT EXISTS ACME_RAW_DB.RAW;

--  DWH Database
CREATE SCHEMA IF NOT EXISTS ACME_DWH_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS ACME_DWH_DB.DWH;

--  Analytics Database
CREATE SCHEMA IF NOT EXISTS ACME_ANALYTICS_DB.REPORTING;

--
----Antes de crear nada: revisemos el estado actual
--
USE ROLE ACCOUNTADMIN;
SHOW DATABASES;

--Paso 1 - Crear Warehouses

CREATE WAREHOUSE IF NOT EXISTS ACME_ETL_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 1
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
/*
Uso:

        cargas RAW
        transformaciones
        procesos batch
        Stored Procedures
        Tasks
*/


-- Warehouse para BI

CREATE WAREHOUSE IF NOT EXISTS ACME_BI_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 1
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;