-- Arquitectura recomendada
    SHOW DATABASES;

--Paso 1 - Eliminar lo anterior 
DROP DATABASE IF EXISTS ACME_RETAIL_DB;

--Paso 2 - Crear las nuevas Databases
CREATE DATABASE IF NOT EXISTS ACME_RAW_DB;
CREATE DATABASE IF NOT EXISTS ACME_DWH_DB;
CREATE DATABASE IF NOT EXISTS ACME_ANALYTICS_DB;

--Paso 3 - Crear Schemas
--  RAW Database
CREATE SCHEMA IF NOT EXISTS ACME_RAW_DB.RAW;

--  DWH Database
CREATE SCHEMA IF NOT EXISTS ACME_DWH_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS ACME_DWH_DB.DWH;

--  Analytics Database
CREATE SCHEMA IF NOT EXISTS ACME_ANALYTICS_DB.REPORTING;

--
----Antes de crear nada: revisemos el estado actual
--
USE ROLE ACCOUNTADMIN;
SHOW DATABASES;

--Paso 1 - Crear Warehouses

CREATE WAREHOUSE IF NOT EXISTS ACME_ETL_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 1
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;
/*
Uso:

        cargas RAW
        transformaciones
        procesos batch
        Stored Procedures
        Tasks
*/


-- Warehouse para BI

CREATE WAREHOUSE IF NOT EXISTS ACME_BI_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 1
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

DESC WAREHOUSE ACME_BI_WH;


SELECT CURRENT_ROLE();


DESC DATABASE ACME_ANALYTICS_DB;
DESC DATABASE ACME_DWH_DB;
DESC DATABASE ACME_RAW_DB;


USE ROLE ACCOUNTADMIN;
USE WAREHOUSE ACME_ETL_WH;
USE DATABASE ACME_RAW_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS CUSTOMERS_RAW
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    EMAIL VARCHAR,
    CITY VARCHAR,
    COUNTRY VARCHAR,
    CREATED_DATE DATE
);


CREATE TABLE IF NOT EXISTS PRODUCTS_RAW
(
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    PRICE NUMBER(10,2)
);


CREATE TABLE IF NOT EXISTS ORDERS_RAW
(
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    ORDER_DATE DATE,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(10,2)
);


INSERT INTO CUSTOMERS_RAW VALUES
(1,'Juan Perez','juan@test.com','Montreal','Canada','2025-01-01'),
(2,'Maria Lopez','maria@test.com','Bogota','Colombia','2025-02-01'),
(3,'John Smith','john@test.com','New York','USA','2025-03-01');


INSERT INTO PRODUCTS_RAW VALUES
(101,'Laptop','Technology',1200),
(102,'Mouse','Technology',50),
(103,'Desk','Furniture',500);


INSERT INTO ORDERS_RAW VALUES
(1001,1,101,'2026-01-10',1,1200),
(1002,1,102,'2026-01-11',2,100),
(1003,2,103,'2026-01-12',1,500),
(1004,3,101,'2026-01-15',1,1200);


USE DATABASE ACME_DWH_DB;

USE SCHEMA STAGING;


CREATE TABLE IF NOT EXISTS STG_CUSTOMERS AS
SELECT *
FROM ACME_RAW_DB.RAW.CUSTOMERS_RAW;


CREATE TABLE IF NOT EXISTS STG_PRODUCTS AS
SELECT *
FROM ACME_RAW_DB.RAW.PRODUCTS_RAW;


CREATE TABLE IF NOT EXISTS STG_ORDERS AS
SELECT *
FROM ACME_RAW_DB.RAW.ORDERS_RAW;


USE SCHEMA DWH;


CREATE TABLE IF NOT EXISTS DIM_CUSTOMER
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    EMAIL VARCHAR,
    CITY VARCHAR,
    COUNTRY VARCHAR
);


CREATE TABLE IF NOT EXISTS DIM_PRODUCT
(
    PRODUCT_KEY NUMBER AUTOINCREMENT,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    PRICE NUMBER(10,2)
);


CREATE TABLE IF NOT EXISTS FACT_SALES
(
    SALES_KEY NUMBER AUTOINCREMENT,
    ORDER_ID NUMBER,
    CUSTOMER_KEY NUMBER,
    PRODUCT_KEY NUMBER,
    ORDER_DATE DATE,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER(10,2)
);



INSERT INTO DIM_CUSTOMER
(
CUSTOMER_ID,
CUSTOMER_NAME,
EMAIL,
CITY,
COUNTRY
)
SELECT
CUSTOMER_ID,
CUSTOMER_NAME,
EMAIL,
CITY,
COUNTRY
FROM STAGING.STG_CUSTOMERS;


INSERT INTO DIM_PRODUCT
(
PRODUCT_ID,
PRODUCT_NAME,
CATEGORY,
PRICE
)
SELECT
PRODUCT_ID,
PRODUCT_NAME,
CATEGORY,
PRICE
FROM STAGING.STG_PRODUCTS;
-- Cargar FA   CT
INSERT INTO FACT_SALES
(
ORDER_ID,
CUSTOMER_KEY,
PRODUCT_KEY,
ORDER_DATE,
QUANTITY,
TOTAL_AMOUNT
)
SELECT

O.ORDER_ID,
C.CUSTOMER_KEY,
P.PRODUCT_KEY,
O.ORDER_DATE,
O.QUANTITY,
O.TOTAL_AMOUNT

FROM ACME_DWH_DB.STAGING.STG_ORDERS O

JOIN DIM_CUSTOMER C
ON O.CUSTOMER_ID = C.CUSTOMER_ID

JOIN DIM_PRODUCT P
ON O.PRODUCT_ID = P.PRODUCT_ID;




--4. ANALYTICS / REPORTING
USE DATABASE ACME_ANALYTICS_DB;
USE SCHEMA REPORTING;
USE WAREHOUSE ACME_BI_WH;


---Crear vistas:

CREATE VIEW IF NOT EXISTS V_SALES AS

SELECT

F.ORDER_ID,
F.ORDER_DATE,
C.CUSTOMER_NAME,
C.COUNTRY,
P.PRODUCT_NAME,
P.CATEGORY,
F.QUANTITY,
F.TOTAL_AMOUNT

FROM ACME_DWH_DB.DWH.FACT_SALES F

JOIN ACME_DWH_DB.DWH.DIM_CUSTOMER C
ON F.CUSTOMER_KEY=C.CUSTOMER_KEY

JOIN ACME_DWH_DB.DWH.DIM_PRODUCT P
ON F.PRODUCT_KEY=P.PRODUCT_KEY;
CREATE VIEW IF NOT EXISTS V_CUSTOMER_SALES AS

SELECT

COUNTRY,
CUSTOMER_NAME,
SUM(TOTAL_AMOUNT) TOTAL_SALES

FROM V_SALES

GROUP BY
COUNTRY,
CUSTOMER_NAME;
CREATE VIEW IF NOT EXISTS V_PRODUCT_SALES AS

SELECT

CATEGORY,
PRODUCT_NAME,
SUM(TOTAL_AMOUNT) TOTAL_SALESl

FROM V_SALES

GROUP BY
CATEGORY,
PRODUCT_NAME;

/*
PASO 1 — Crear Access Roles
Usamos SECURITYADMIN porque administrar roles es responsabilidad de seguridad.
*/
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS AR_ACME_RAW_WRITE;
CREATE ROLE IF NOT EXISTS AR_ACME_DWH_WRITE;
CREATE ROLE IF NOT EXISTS AR_ACME_DWH_READ;
CREATE ROLE IF NOT EXISTS AR_ACME_REPORTING_READ;


/*PASO 2 — Crear Functional Roles*/
CREATE ROLE IF NOT EXISTS FR_ACME_DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS FR_ACME_BI_ANALYST;
CREATE ROLE IF NOT EXISTS FR_ACME_BUSINESS_USER;


/*PASO 3 — Asignar Access Roles a Functional Roles
Data Engineer 
Necesita:
RAW
STAGING
DWH
*/
GRANT ROLE AR_ACME_RAW_WRITE    TO ROLE FR_ACME_DATA_ENGINEER;
GRANT ROLE AR_ACME_DWH_WRITE    TO ROLE FR_ACME_DATA_ENGINEER;

SHOW GRANTS TO ROLE FR_ACME_DATA_ENGINEER ;
/*
BI Analyst
Necesita:
Leer DWH
Leer Reporting
*/
GRANT ROLE AR_ACME_DWH_READ         TO ROLE FR_ACME_BI_ANALYST;
GRANT ROLE AR_ACME_REPORTING_READ   TO ROLE FR_ACME_BI_ANALYST;

/*
Business User
Solo reportes:
*/
GRANT ROLE AR_ACME_REPORTING_READ   TO ROLE FR_ACME_BUSINESS_USER;


/*
PASO 4 — Asignar permisos a Access Roles
Ahora los Access Roles reciben permisos sobre objetos.
4.1 RAW WRITE
*/
USE ROLE ACCOUNTADMIN;
GRANT USAGE ON DATABASE ACME_RAW_DB     TO ROLE AR_ACME_RAW_WRITE;
GRANT USAGE ON SCHEMA ACME_RAW_DB.RAW   TO ROLE AR_ACME_RAW_WRITE;

-- Tablas existentes:
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL     TABLES IN SCHEMA ACME_RAW_DB.RAW TO ROLE AR_ACME_RAW_WRITE;

-- Tablas futuras:
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE  TABLES IN SCHEMA ACME_RAW_DB.RAW TO ROLE AR_ACME_RAW_WRITE;

/*4.2 DWH WRITE
Este rol controla STAGING y DWH.
*/ 
GRANT USAGE ON DATABASE ACME_DWH_DB         TO ROLE AR_ACME_DWH_WRITE;
-- STAGING:

GRANT USAGE ON SCHEMA ACME_DWH_DB.STAGING   TO ROLE AR_ACME_DWH_WRITE;

GRANT SELECT, INSERT, UPDATE, DELETE        ON ALL TABLES IN SCHEMA     ACME_DWH_DB.STAGING TO ROLE AR_ACME_DWH_WRITE;
GRANT SELECT, INSERT, UPDATE, DELETE        ON FUTURE TABLES IN SCHEMA  ACME_DWH_DB.STAGING TO ROLE AR_ACME_DWH_WRITE;

-- DWH:

GRANT USAGE ON SCHEMA ACME_DWH_DB.DWH TO ROLE AR_ACME_DWH_WRITE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL     TABLES IN SCHEMA ACME_DWH_DB.DWH TO ROLE AR_ACME_DWH_WRITE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE  TABLES IN SCHEMA ACME_DWH_DB.DWH TO ROLE AR_ACME_DWH_WRITE;

/*
4.3 DWH READ
Para analistas:
*/
GRANT USAGE ON DATABASE ACME_DWH_DB         TO ROLE AR_ACME_DWH_READ;
GRANT USAGE ON SCHEMA   ACME_DWH_DB.DWH     TO ROLE AR_ACME_DWH_READ;

--
-- PASO 5 — Warehouse Access
-- 
-- Los warehouses también son objetos protegidos.
--ETL Warehouse
--Data Engineers:
GRANT USAGE ON WAREHOUSE                ACME_ETL_WH         TO ROLE FR_ACME_DATA_ENGINEER;
-- Lectura:
GRANT SELECT ON ALL TABLES IN SCHEMA    ACME_DWH_DB.DWH     TO ROLE AR_ACME_DWH_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ACME_DWH_DB.DWH     TO ROLE AR_ACME_DWH_READ;

--
-- 4.4 REPORTING READ
--
-- Para BI y usuarios:

GRANT USAGE ON DATABASE ACME_ANALYTICS_DB               TO ROLE AR_ACME_REPORTING_READ;
GRANT USAGE ON SCHEMA   ACME_ANALYTICS_DB.REPORTING     TO ROLE AR_ACME_REPORTING_READ;

--
--Vistas actuales:
--

GRANT SELECT ON ALL VIEWS IN SCHEMA     ACME_ANALYTICS_DB.REPORTING TO ROLE AR_ACME_REPORTING_READ;

--
--Vistas futuras:
--

GRANT SELECT ON FUTURE VIEWS IN SCHEMA  ACME_ANALYTICS_DB.REPORTING TO ROLE AR_ACME_REPORTING_READ;


--
-- 4.5 REPORTING write
--
-- Para BI y usuarios:
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS AR_ACME_REPORTING_WRITE;

GRANT USAGE ON DATABASE ACME_ANALYTICS_DB               TO ROLE AR_ACME_REPORTING_WRITE;
GRANT USAGE ON SCHEMA   ACME_ANALYTICS_DB.REPORTING     TO ROLE AR_ACME_REPORTING_WRITE;

GRANT CREATE VIEW ON SCHEMA ACME_ANALYTICS_DB.REPORTING TO ROLE AR_ACME_REPORTING_WRITE;

GRANT ROLE AR_ACME_REPORTING_WRITE    TO ROLE FR_ACME_DATA_ENGINEER;
SHOW GRANTS TO ROLE FR_ACME_DATA_ENGINEER ;

SHOW ROLES LIKE 'AR_ACME%';
SHOW ROLES LIKE 'FR_ACME%';

SHOW GRANTS TO ROLE AR_ACME_REPORTING_READ ;
SHOW GRANTS TO ROLE AR_ACME_DWH_WRITE      ;
SHOW GRANTS TO ROLE AR_ACME_DWH_READ       ;
SHOW GRANTS TO ROLE AR_ACME_RAW_WRITE      ;
SHOW GRANTS TO ROLE AR_ACME_REPORTING_WRITE;

SHOW FUTURE GRANTS TO ROLE AR_ACME_REPORTING_READ ;
SHOW FUTURE GRANTS TO ROLE AR_ACME_REPORTING_WRITE;
SHOW FUTURE GRANTS TO ROLE AR_ACME_DWH_WRITE      ;
SHOW FUTURE GRANTS TO ROLE AR_ACME_DWH_READ       ;
SHOW FUTURE GRANTS TO ROLE AR_ACME_RAW_WRITE      ;


SHOW VIEWS IN SCHEMA ACME_ANALYTICS_DB.REPORTING;

USE ROLE ACCOUNTADMIN;
GRANT OWNERSHIP ON VIEW ACME_ANALYTICS_DB.REPORTING.V_SALES 			TO ROLE AR_ACME_REPORTING_WRITE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON VIEW ACME_ANALYTICS_DB.REPORTING.V_CUSTOMER_SALES 	TO ROLE AR_ACME_REPORTING_WRITE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON VIEW ACME_ANALYTICS_DB.REPORTING.V_PRODUCT_SALES 	TO ROLE AR_ACME_REPORTING_WRITE COPY CURRENT GRANTS;

SHOW GRANTS ON VIEW ACME_ANALYTICS_DB.REPORTING.V_SALES;



SHOW GRANTS TO ROLE FR_ACME_DATA_ENGINEER;
SHOW GRANTS TO ROLE FR_ACME_BI_ANALYST;
SHOW GRANTS TO ROLE FR_ACME_BUSINESS_USER;

SHOW GRANTS OF ROLE FR_ACME_DATA_ENGINEER;


SHOW GRANTS OF ROLE AR_ACME_RAW_WRITE; -- para ver si alguien lo tiene asignado.

CREATE ROLE tasty_role;

SHOW GRANTS TO ROLE tasty_role;
GRANT CREATE DATABASE ON ACCOUNT  TO ROLE tasty_role;

SELECT CURRENT_USER;
GRANT ROLE tasty_role TO USER FELIPEXCORP;
USE ROLE tasty_role;

CREATE WAREHOUSE tasty_test_wh;

USE ROLE ACCOUNTADMIN;
 SHOW GRANTS TO USER FELIPEXCORP;

 SHOW GRANTS TO ROLE USERADMIN;
SHOW GRANTS OF ROLE tasty_role;