select * from TASTY_BYTES_SAMPLE_DATA.RAW_POS.MENU
WHERE ITEM_CATEGORY = 'Snack' and ITEM_SUBCATEGORY = 'Warm Option';

select ITEM_SUBCATEGORY , MAX(SALE_PRICE_USD) from TASTY_BYTES_SAMPLE_DATA.RAW_POS.MENU
WHERE ITEM_SUBCATEGORY IN ('Hot Option', 'Warm Option', 'Cold Option')
GROUP BY 1
ORDER BY 2 DESC;


select ITEM_SUBCATEGORY , MAX(SALE_PRICE_USD) from TASTY_BYTES_SAMPLE_DATA.RAW_POS.MENU
GROUP BY 1
ORDER BY 2 DESC;